### ISSUE TITLE
Requesting the addition of "Mirror Shots" in freeplay checkpoint options

### ISSUE THREAD

**Issue by herculuis** [NitrOP7674/FreeplayCheckpoint#16]
Hi, I am suggesting an idea, I am not sure if it's possible to do so, but I am just pitching in. 
In bakkesmod custom training, there is an option called "mirror shots", which let's you to mirror the training shot from the opposite side, which really helps a lot. If it's possible, could you add this feature also in Freeplay checkpoint, so that we can mirror the shots we save. FRPCP already have variance option, now mirror shots will really make it a lot closer to complete, I think. Thanks.

**Comment by Paquette1111** [comment]
I 2nd this comment :)

**Comment by NitrOP7674** [comment]
I added this as an option in the plugin settings!  Please try it out and let me know if it works well for you:

https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.5.0-pre2/CheckpointPlugin-v1.5.0-pre2.zip

Note that I ran into a minor problem with this feature that makes it undesirable in some situations.  I air roll left immediately after jumping off a side wall to go into an air dribble, which imparts left spin on my car.  I then take a snapshot starting momentarily after this.  When the shot is mirrored, this translates into right spin (as expected), since it is a full mirror.  But since I only use air roll left in this situation, it takes some extra time to cancel the right spin and begin left spinning.

Also, for some crazy reason, I wasn't able to mirror left-to-right.  The orientation of the car (represented as a Rotation) was always 180 degrees off after this reflection was performed.  However, the same technique works perfectly when mirroring blue-to-orange.  So the goal you are scoring on will be the opposite color when the mirroring happens.  I'm not all that happy about this, but I wasn't able to sort out how to make the mirroring work correctly the other way.

**Comment by NitrOP7674** [comment]
> I'm not all that happy about this, but I wasn't able to sort out how to make the mirroring work correctly the other way.

I believe I have fixed this and made a new test release: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.5.0-pre3/CheckpointPlugin-v1.5.0-pre3.zip

It should be effectively the same but the color of the goal won't change.  Please help me to make sure this release is stable if possible, so I can feel a little more confident pushing it to http://bakkesplugins.com.

**Comment by herculuis** [comment]
Sorry bro, I was out of my home for like two weeks so couldn't check it. Now, I checked it, and it works pretty well, I mean, it's working fine in terms of the Air roll issue. I think, After you press the reset button, if you take the shot and wait just a little while, then you press reset button again, then it mirrors the shot, but if you press reset button pretty much immediately while taking the shot, it resets the original shot. I will admit using the "Same" air roll for the mirror shot feels awkward, but, I use both Air roll (For the most part, although Left one is my go to move), It's not really an issue for me.
I will keep testing this, and let you know If I see any other issue. Color of the goal doesn't really matter to me in freeplay, so whatever way it works doesn't matter to me, Thanks a lot for adding this feature.

**Comment by herculuis** [comment]
Oh, I totally didn't see the "Randomly" part of the mirror shot option in the FPC. So, I guess it randomly mirror shot or reset the same shot if we keep pressing the Reset shot button.

**Comment by NitrOP7674** [comment]
> Oh, I totally didn't see the "Randomly" part of the mirror shot option in the FPC. So, I guess it randomly mirror shot or reset the same shot if we keep pressing the Reset shot button.

Exactly.  In the next pre-release version, which you can find [here](https://github.com/NitrOP7674/FreeplayCheckpoint/releases/tag/v1.5.0-pre4), I added a command that you can bind to a button/key to make it mirror on demand.  That might be more what you are looking for.  There's also a couple other new features in there, too, listed in the release notes.  I haven't had any problems with this version at all, so I'll probably push it to bakkesplugins.com in a few days.  You might want to backup your saved checkpoints file before using it, just in case.  It's in the bakkesmod folder (File > Open Bakkesmod Folder in the UI) under "data" and is called "freeplaycheckpoint.data" by default.

**Comment by herculuis** [comment]
Thanks a lot. I will check out the version 4. And yes, I will have to backup my 70 shots, those are precious. Thanks for making this feature a reality, much love.

**Comment by herculuis** [comment]
I tried version 4, and really, this was what I was looking for, I unchecked random mirroring option, then bound the cpt_mirror_state command or something like that to the dpad down. Now, I can manually mirror shots with the dpad down button, basically like bakkesmod custom training. Great work.

**Comment by NitrOP7674** [comment]
👀 I've been using bakkesmod for years and never knew that dpad down mirrored shots in custom training manually.  I thought you had to randomly mirror and keep reloading the shot to get the side you wanted.

I was using dpad down in my own config for this when testing.  I'll add something to the settings dialog for this, then, since it seems like a natural fit.

**Comment by herculuis** [comment]
Oh my, you didn't know!! lol. No prob. Yeah, it does feel like the natural fit, I think most people use dpad down for mirroring in custom training in bkmd. Either way, great work, man.
