### ISSUE TITLE
Can't see boost while rewinding

### ISSUE THREAD

**Issue by maciekwiso** [NitrOP7674/FreeplayCheckpoint#27]
When rewinding you can't see boost from you car, and so it doesn't show when you were boosting.
It'd be very useful to see exactly when you were boosting when you're reviewing your shots while training mechanics .

**Comment by NitrOP7674** [comment]
I agree it would be nice to be able to see the boost being active/not while rewinding.  However, I tested it out and found that the trails are pretty intrusive when rewinding (they end up in front and inside of the car).  I'll see if there is some way to clear away the trails or to not produce them, but otherwise I'm not sure this is a good idea.  At best there could be an option to enable it.

**Comment by maciekwiso** [comment]
So maybe instead of showing actual boost, you could show in some other way when boost was active? Like an icon or something that'd show up, or light up when boost was active?

**Comment by NitrOP7674** [comment]
Added as an option in the latest pre-release: https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre5/CheckpointPlugin-v1.7.0-pre5.zip

**Comment by NitrOP7674** [comment]
UPDATE: Please use https://github.com/NitrOP7674/FreeplayCheckpoint/releases/download/v1.7.0-pre5-2/CheckpointPlugin-v1.7.0-pre5-2.zip instead; the other version had a bug that caused crashes in it.
