### ISSUE TITLE
Bug: Rocket League "Reset Shot" command overrides "cpt_do_checkpoint" function and doesn't reset properly to checkpoints

### ISSUE THREAD

**Issue by Serchiot** [NitrOP7674/FreeplayCheckpoint#33]
As description said, if I hold down gas (default RT) and reset a shot, it not load from checkpoint. This seems to be what caused my previous issue that I already closed where I have to double tap checkpoint to properly load it.

**Comment by Serchiot** [comment]
After additional testing this seems to simply be caused by a longer pause. Is there maybe a setting that makes it so after a certain amount of time it does not load a checkpoint but instead resets the shot normally?

**Comment by NitrOP7674** [comment]
I'm not exactly sure what you mean by "pause" but if you're talking about the feature to load a checkpoint when you hit the "reset shot" button, there's a setting for that time in the bindings section of the plugin settings.

**Comment by Serchiot** [comment]
After a bit further research it seems that the rocket league reset shot button (which I have also set to the back button) is interferring with the checkpoint plugin. If I remove the reset shot button or set it to another button, it works as it should. 
This didn't happen on previous patches, maybe Rocket League somehow overrides your reset to checkpoint function now.

**Comment by NitrOP7674** [comment]
I think this is related to #29.  A semi-recent RL change made some changes in this plugin necessary to work around problems.  These workarounds made binding the same button for both functions not work.  However, a new option was added to this plugin to make the "reset shot" button restore the latest checkpoint instead of resetting (unless you push it twice) which I mentioned above, which at least for me would be the most common reason to want to do this.  You can read through that issue for more info if interested.

**Comment by Serchiot** [comment]
If you mean the "reset button loads last checkpoint instead of resetting if loaded before X seconds" then it doesn't properly work. Every second input resets the shot normally instead of reloading the checkpoint. I have attached a streamable.com link showcasing the issue if that is of help.
https://streamable.com/plug6k
