### ISSUE TITLE
Storing Rewind/Forward data in Checkpoints

### ISSUE THREAD

**Issue by SporkSlinger** [NitrOP7674/FreeplayCheckpoint#52]
Feature Request: Checkpoint-Based Training with Rewind/FF

I don't know how possible it is.
It would be nice to have stored forward information, so that you can rewind/ff from a checkpoint. This would encourage objective-based training and make sharable training packs that have a specific objective in mind since you can see the shot you're trying to do.

end goal: Sharable Training Packs with Objective-Based Training
Thank you for the plugin!

**Comment by NitrOP7674** [comment]
Unfortunately, such a feature would be a pretty different plugin, or at least require a lot of work that I don't have time to do.

The amount of data a stored checkpoint consumes would increase significantly as well...  I'm going to close this since it's not really feasible.  Anyone in the world should feel free to fork this plugin and use it as a base for this work if they desire.
